# Numpy 
Mempelajari dasar-dasar numpy

In [45]:
import numpy as np
np.__version__

'1.24.2'

## Python List

In [8]:
ipk_list = [4.0, 3.56, 3.76, 3.61]

In [9]:
# MENAMBAHKAN VALUE KE LIST
ipk_list.append(3.66)
ipk_list

[4.0, 3.56, 3.76, 3.61, 3.66]

# Array Multidimensi

In [18]:
students_ipk = np.array([
    [4.0, 3.3, 3.5, 4.0],
    [3.96, 3.92, 4.0, 4.0],
    [3.2, 3.8, 4.0, 4.0]
], np.float16)
students_ipk

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [14]:
# Melihat dimensi dari array
students_ipk.ndim

2

In [15]:
# Mendapatkan shape dari array
students_ipk.shape

(3, 4)

In [20]:
# Mengakses berdasarkan indexs
students_ipk[2]

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [21]:
students_ipk[2][3]

4.0

## Study Log Multidimensi

In [4]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [5]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint16)

In [6]:
study_minutes[1][0] = 60
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

In [8]:
# Method random states
# Angka di dlm kurung randomState itu bebas aja, bisa 42, 46 atau angka lainnya
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [9]:
fake_log[7]

95

In [12]:
# Notasi 1 => Menjadi list
[fake_log[1], fake_log[78]]

[122, 81]

In [13]:
# Notasi 2 => Menjadi array
fake_log[[1, 78]]

array([122,  81], dtype=uint16)

In [15]:
# Konstruksi array baru menggunakan index yang lama
index = np.array([
    [1,2],
    [2,67]
])
fake_log[index]

array([[122, 128],
       [128,  50]], dtype=uint16)

In [16]:
# Array tidak dapat diubah, 
# Namun kita bisa memanfaatkan numpy untuk mengubahnya, sebelumnya kita harus append
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

## Slicing

In [17]:
practice = np.arange(42)
practice.shape = (7, 6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [21]:
practice[2][1]

13

In [25]:
practice[2,1]

13

In [24]:
# Mendapatkan elemen dari practice baris ke 2 hingga sebelum 5
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
practice[2:5, 3]

array([15, 21, 27])

In [27]:
# Mendapatkan elemen 3 dan seterusnya
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

## Copy & View di array
Berbeda dengan list di python yang bisa langsung dicopy dengan cara biasa, jika kita melakukan hal yang sama maka array akan membuat view dari data aslinya sehingga jika kita ubah data aslinya pun ikut berubah. 

### Contoh copy list

In [28]:
contoh_copas = [1, 2, 3]
contoh_copas_copy = contoh_copas[:]
contoh_copas, contoh_copas_copy

([1, 2, 3], [1, 2, 3])

In [29]:
contoh_copas_copy[0] = 12345
contoh_copas, contoh_copas_copy

([1, 2, 3], [12345, 2, 3])

### Contoh copy di array
Dua-duanya berubah, karena menampilkan view bukan hasil copy-an

In [36]:
not_copied = practice[:]
not_copied[0, 0] = 12345
practice, not_copied

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [37]:
not_copied.base is practice

True

In [39]:
not_copied.base is contoh_copas

False

## Filter array dengan Kondisi

In [42]:
study_minutes[study_minutes < 60]
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

# Aljabar Linear

In [60]:
from numpy import linalg

In [61]:
orders = np.array([
    [2, 0, 0, 0],
    [1, 0, 2, 4],
    [1, 0, 2, 4],
    [4, 6, 0, 2]
])
totals = np.array([
    20000, 
    32000, 
    20000, 
    61000
])
prices= np.linalg.solve(orders, totals)
prices

LinAlgError: Singular matrix

In [59]:
# Perkalian matriks
orders @ totals

array([ 40000, 304000, 304000, 394000])

## Fungsi Universal

In [63]:
a, b = np.split(np.arange(1, 11), 2)
a, b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [64]:
a + b

array([ 7,  9, 11, 13, 15])

In [65]:
a - b

array([-5, -5, -5, -5, -5])

In [66]:
a @ b

130

In [67]:
b * a

array([ 6, 14, 24, 36, 50])

In [73]:
#  Menambahkan array dengan skalar
c = a + 9
c

array([10, 11, 12, 13, 14])

In [76]:
c + np.repeat(3, 5)

array([13, 14, 15, 16, 17])

In [79]:
x = np.arange(9.0).reshape(3, 3)
y = np.arange(3.0)
x, y

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [80]:
np.add(x, y)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])