In [1]:
M = np.random.random((5,5))

NameError: name 'np' is not defined

import numpy as np


In [5]:
M = np.random.random((5,5))
print (M)


[[0.67500445 0.64485238 0.89839408 0.45852567 0.61770089]
 [0.02007835 0.72665569 0.71049256 0.2295405  0.04458089]
 [0.70718714 0.39457953 0.2735488  0.40572027 0.49661241]
 [0.05709657 0.03798284 0.73374887 0.32433085 0.41836943]
 [0.6659343  0.94971113 0.12322389 0.01087217 0.35086727]]


In [6]:
M.min(axis=0)

array([0.02007835, 0.03798284, 0.12322389, 0.01087217, 0.04458089])

In [11]:
Mat = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
Mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
Mat.T.Shape

AttributeError: 'numpy.ndarray' object has no attribute 'Shape'

In [17]:
mat.Transposed = Mat.T

NameError: name 'mat' is not defined

In [25]:
one_3d = np.ones((3, 3, 3, 4))

In [27]:
one_3d.mean()

1.0

In [30]:
one_3d.shape

(3, 3, 3, 4)

In [36]:
one_3d.reshape(1, 108)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
one_3d.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [41]:
mat_per1 = np.array([
    [1,2],
    [3,5]
])
mat_has = np.array([1,2])

np.linalg.solve(mat_per1, mat_has)

array([-1.,  1.])

In [44]:
# Library numpy ngga spesifik untuk datascien
# Bisa dipake untuk keperluan scientifik lain

In [46]:
# model regresi, untuk ngecek hasil prediksi sama data aktualnya
data_aktual = np.random.random(100)

In [50]:
data_prediksi = np.random.random(100)

In [53]:
1/len(data_aktual) * np.sum(np.square(data_aktual - data_prediksi))

0.14956174713403103